In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import ast
import os

from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
movies_path = "/mnt/data/tmdb_5000_movies.csv"
credits_path = "/mnt/data/tmdb_5000_credits.csv"

movies = pd.read_csv("C:/Users/Varsha/Downloads/tmdb_5000_movies.csv/tmdb_5000_movies.csv")
credits = pd.read_csv("C:/Users/Varsha/Downloads/tmdb_5000_credits.csv/tmdb_5000_credits.csv")

print("Movies dataset loaded!")
print("Credits dataset loaded!")

Movies dataset loaded!
Credits dataset loaded!

In [5]:
print("Movies Dataset Shape:")
print(movies.shape)

print("\nCredits Dataset Shape:")
print(credits.shape)

print("\nMovies Columns:")
print(movies.columns.tolist())

print("\nCredits Columns:")
print(credits.columns.tolist())

Movies Dataset Shape:
(4803, 20)

Credits Dataset Shape:
(4803, 4)

Movies Columns:
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count']

Credits Columns:
['movie_id', 'title', 'cast', 'crew']

In [6]:
display(movies.head())

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
display(credits.head())

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
print("MOVIES DATASET")
movies.info()

print("\n\nCREDITS DATASET")
credits.info()

MOVIES DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB


CREDITS DATASET
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [9]:
print("Missing values in Movies dataset:")
print(movies.isnull().sum())

print("\nMissing values in Credits dataset:")
print(credits.isnull().sum())

Missing values in Movies dataset:
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

Missing values in Credits dataset:
movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [10]:
print("Duplicate rows in Movies:", movies.duplicated().sum())
print("Duplicate rows in Credits:", credits.duplicated().sum())

Duplicate rows in Movies: 0
Duplicate rows in Credits: 0

In [11]:
df = movies.merge(
    credits,
    left_on="id",
    right_on="movie_id",
    how="left"
)

print("Merged Dataset Shape:")
print(df.shape)

display(df.head())

Merged Dataset Shape:
(4803, 24)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
df = df.drop(
    columns=["movie_id", "title_y"],
    errors="ignore"
)

df = df.rename(
    columns={"title_x": "title"}
)

print(df.shape)
print(df.columns.tolist())

(4803, 22)
['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language', 'original_title', 'overview', 'popularity', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'vote_average', 'vote_count', 'cast', 'crew']

In [13]:
selected_columns = [
    "id",
    "title",
    "genres",
    "budget",
    "revenue",
    "release_date",
    "runtime",
    "popularity",
    "vote_average",
    "vote_count",
    "original_language",
    "production_companies",
    "cast",
    "crew"
]

df = df[
    [col for col in selected_columns if col in df.columns]
]

display(df.head())

,id,title,genres,budget,revenue,release_date,runtime,popularity,vote_average,vote_count,original_language,production_companies,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",237000000,2787965087,2009-12-10,162.0,150.437577,7.2,11800,en,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",300000000,961000000,2007-05-19,169.0,139.082615,6.9,4500,en,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",245000000,880674609,2015-10-26,148.0,107.376788,6.3,4466,en,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",250000000,1084939099,2012-07-16,165.0,112.312950,7.6,9106,en,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",260000000,284139100,2012-03-07,132.0,43.926995,6.1,2124,en,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
df["release_date"] = pd.to_datetime(
    df["release_date"],
    errors="coerce"
)

df["year"] = df["release_date"].dt.year

print(df[["title", "release_date", "year"]].head())

                                      title release_date    year
0                                    Avatar   2009-12-10  2009.0
1  Pirates of the Caribbean: At World's End   2007-05-19  2007.0
2                                   Spectre   2015-10-26  2015.0
3                     The Dark Knight Rises   2012-07-16  2012.0
4                               John Carter   2012-03-07  2012.0

In [15]:
numeric_columns = [
    "budget",
    "revenue",
    "runtime",
    "popularity",
    "vote_average",
    "vote_count"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

print(df[numeric_columns].dtypes)

budget            int64
revenue           int64
runtime         float64
popularity      float64
vote_average    float64
vote_count        int64
dtype: object

In [16]:
print("Budget = 0:", (df["budget"] == 0).sum())
print("Revenue = 0:", (df["revenue"] == 0).sum())

Budget = 0: 1037
Revenue = 0: 1427

In [17]:
df["profit"] = df["revenue"] - df["budget"]

display(
    df[
        ["title", "budget", "revenue", "profit"]
    ].head(10)
)

                                      title     budget     revenue      profit
0                                    Avatar  237000000  2787965087  2550965087
1  Pirates of the Caribbean: At World's End  300000000   961000000   661000000
2                                   Spectre  245000000   880674609   635674609
3                     The Dark Knight Rises  250000000  1084939099   834939099
4                               John Carter  260000000   284139100    24139100
5                              Spider-Man 3  258000000   890871626   632871626
6                                   Tangled  260000000   591794936   331794936
7                   Avengers: Age of Ultron  280000000  1405403694  1125403694
8    Harry Potter and the Half-Blood Prince  250000000   933959197   683959197
9        Batman v Superman: Dawn of Justice  250000000   873260194   623260194

In [18]:
df["roi"] = np.where(
    df["budget"] > 0,
    (
        (df["revenue"] - df["budget"])
        / df["budget"]
    ) * 100,
    np.nan
)

display(
    df[
        ["title", "budget", "revenue", "roi"]
    ].head(10)
)

,title,budget,revenue,roi
0,Avatar,237000000,2787965087,1076.356577
1,Pirates of the Caribbean: At World's End,300000000,961000000,220.333333
2,Spectre,245000000,880674609,259.459024
3,The Dark Knight Rises,250000000,1084939099,333.975640
4,John Carter,260000000,284139100,9.284269
5,Spider-Man 3,258000000,890871626,245.299080
6,Tangled,260000000,591794936,127.613437
7,Avengers: Age of Ultron,280000000,1405403694,401.929891
8,Harry Potter and the Half-Blood Prince,250000000,933959197,273.583679
9,Batman v Superman: Dawn of Justice,250000000,873260194,249.304078

In [19]:
df["rating_category"] = pd.cut(
    df["vote_average"],
    bins=[
        -np.inf,
        5,
        7,
        8,
        np.inf
    ],
    labels=[
        "Low",
        "Average",
        "Good",
        "Excellent"
    ]
)

display(
    df[
        ["title", "vote_average", "rating_category"]
    ].head(10)
)

                                      title  vote_average rating_category
0                                    Avatar           7.2            Good
1  Pirates of the Caribbean: At World's End           6.9         Average
2                                   Spectre           6.3         Average
3                     The Dark Knight Rises           7.6            Good
4                               John Carter           6.1         Average
5                              Spider-Man 3           5.9         Average
6                                   Tangled           7.4            Good
7                   Avengers: Age of Ultron           7.3            Good
8    Harry Potter and the Half-Blood Prince           7.4            Good
9        Batman v Superman: Dawn of Justice           5.7         Average

In [20]:
def extract_names(value):
    try:
        data = ast.literal_eval(value)

        if isinstance(data, list):
            return [
                item["name"]
                for item in data
                if isinstance(item, dict)
                and "name" in item
            ]

    except (ValueError, SyntaxError, TypeError):
        return []

    return []


df["genre_list"] = df["genres"].apply(
    extract_names
)

df["genre"] = df["genre_list"].apply(
    lambda x: ", ".join(x)
)

display(
    df[
        ["title", "genre"]
    ].head(10)
)

,title,genre
0,Avatar,"Action, Adventure, Fantasy, Science Fiction"
1,Pirates of the Caribbean: At World's End,"Adventure, Fantasy, Action"
2,Spectre,"Action, Adventure, Crime"
3,The Dark Knight Rises,"Action, Crime, Drama, Thriller"
4,John Carter,"Action, Adventure, Science Fiction"
5,Spider-Man 3,"Fantasy, Action, Adventure"
6,Tangled,"Animation, Family"
7,Avengers: Age of Ultron,"Action, Adventure, Science Fiction"
8,Harry Potter and the Half-Blood Prince,"Adventure, Fantasy, Family"
9,Batman v Superman: Dawn of Justice,"Action, Adventure, Fantasy"

In [21]:
genre_df = df[
    ["id", "title", "genre_list", "vote_average",
     "budget", "revenue", "profit", "roi"]
].copy()

genre_df = genre_df.explode(
    "genre_list"
)

genre_df = genre_df.rename(
    columns={"genre_list": "genre"}
)

genre_df = genre_df.dropna(
    subset=["genre"]
)

display(genre_df.head(10))

,id,title,genre,vote_average,budget,revenue,profit,roi
0,19995,Avatar,Action,7.2,237000000,2787965087,2550965087,1076.356577
0,19995,Avatar,Adventure,7.2,237000000,2787965087,2550965087,1076.356577
0,19995,Avatar,Fantasy,7.2,237000000,2787965087,2550965087,1076.356577
0,19995,Avatar,Science Fiction,7.2,237000000,2787965087,2550965087,1076.356577
1,285,Pirates of the Caribbean: At World's End,Adventure,6.9,300000000,961000000,661000000,220.333333
1,285,Pirates of the Caribbean: At World's End,Fantasy,6.9,300000000,961000000,661000000,220.333333
1,285,Pirates of the Caribbean: At World's End,Action,6.9,300000000,961000000,661000000,220.333333
2,206647,Spectre,Action,6.3,245000000,880674609,635674609,259.459024
2,206647,Spectre,Adventure,6.3,245000000,880674609,635674609,259.459024
2,206647,Spectre,Crime,6.3,245000000,880674609,635674609,259.459024

In [22]:
total_movies = df["id"].nunique()

average_rating = df["vote_average"].mean()

total_revenue = df["revenue"].sum()

average_revenue = df["revenue"].mean()

average_budget = df["budget"].mean()

average_roi = df["roi"].mean()

print("========== MOVIE ANALYTICS KPIs ==========")

print(f"Total Movies       : {total_movies:,}")
print(f"Average Rating     : {average_rating:.2f}")
print(f"Total Revenue      : {total_revenue:,.0f}")
print(f"Average Revenue    : {average_revenue:,.0f}")
print(f"Average Budget     : {average_budget:,.0f}")
print(f"Average ROI        : {average_roi:.2f}%")

========== MOVIE ANALYTICS KPIs ==========
Total Movies       : 4,803
Average Rating     : 6.09
Total Revenue      : 395,097,847,444
Average Revenue    : 82,260,639
Average Budget     : 29,045,040
Average ROI        : 253248.95%

In [23]:
movies_by_genre = (
    genre_df["genre"]
    .value_counts()
)

print(movies_by_genre)

genre
Drama              2297
Comedy             1722
Thriller           1274
Action             1154
Romance             894
Adventure           790
Crime               696
Science Fiction     535
Horror              519
Family              513
Fantasy             424
Mystery             348
Animation           234
History             197
Music               185
War                 144
Documentary         110
Western              82
Foreign              34
TV Movie              8
Name: count, dtype: int64

In [24]:
rating_by_genre = (
    genre_df
    .groupby("genre")["vote_average"]
    .mean()
    .sort_values(
        ascending=False
    )
)

display(
    rating_by_genre
    .round(2)
    .to_frame("Average Rating")
)

                 Average Rating
genre
History                    6.72
War                        6.71
Drama                      6.39
Music                      6.36
Foreign                    6.35
Animation                  6.34
Crime                      6.27
Documentary                6.24
Romance                    6.21
Mystery                    6.18
Western                    6.18
Adventure                  6.16
Fantasy                    6.10
Family                     6.03
Thriller                   6.01
Science Fiction            6.01
Action                     5.99
Comedy                     5.95
TV Movie                   5.66
Horror                     5.63

In [25]:
revenue_by_genre = (
    genre_df
    .groupby("genre")["revenue"]
    .mean()
    .sort_values(
        ascending=False
    )
)

display(
    revenue_by_genre
    .to_frame("Average Revenue")
)

                 Average Revenue
genre
Animation           2.256930e+08
Adventure           2.086602e+08
Fantasy             1.933542e+08
Family              1.623455e+08
Science Fiction     1.524565e+08
Action              1.412131e+08
War                 8.415587e+07
Thriller            8.104429e+07
Mystery             7.830093e+07
Comedy              7.128950e+07
Crime               6.615066e+07
Romance             6.000239e+07
History             5.752356e+07
Drama               5.211623e+07
Music               4.845595e+07
Western             4.624596e+07
Horror              4.354508e+07
Documentary         9.838888e+06
Foreign             3.646515e+05
TV Movie            0.000000e+00

In [26]:
roi_by_genre = (
    genre_df
    .groupby("genre")["roi"]
    .mean()
    .sort_values(
        ascending=False
    )
)

display(
    roi_by_genre
    .round(2)
    .to_frame("Average ROI %")
)

                 Average ROI %
genre
Comedy               648717.97
Drama                491155.79
Horror               250933.00
Thriller              93565.32
Documentary           10764.39
Mystery                5946.09
Animation               450.23
Science Fiction         437.77
Fantasy                 424.98
Music                   421.40
Family                  359.15
War                     345.45
Romance                 329.59
Western                 323.33
Adventure               309.84
Crime                   271.15
History                 253.09
Action                  223.70
Foreign                 -71.20
TV Movie               -100.00

In [27]:
movies_by_year = (
    df
    .groupby("year")
    .size()
    .reset_index(
        name="movie_count"
    )
)

display(
    movies_by_year.tail(20)
)

      year  movie_count
70  1998.0          133
71  1999.0          171
72  2000.0          166
73  2001.0          183
74  2002.0          203
75  2003.0          169
76  2004.0          204
77  2005.0          217
78  2006.0          237
79  2007.0          195
80  2008.0          227
81  2009.0          247
82  2010.0          225
83  2011.0          223
84  2012.0          208
85  2013.0          231
86  2014.0          238
87  2015.0          216
88  2016.0          104
89  2017.0            1

In [28]:
revenue_by_year = (
    df
    .groupby("year")["revenue"]
    .sum()
    .reset_index()
)

display(
    revenue_by_year
    .sort_values(
        "revenue",
        ascending=False
    )
    .head(10)
)

      year      revenue
84  2012.0  24141710246
86  2014.0  24120490589
85  2013.0  23411493295
87  2015.0  22775024221
81  2009.0  21072651506
83  2011.0  20516921160
82  2010.0  20348574768
80  2008.0  18146479803
78  2006.0  16635892750
79  2007.0  16491621655

In [29]:
correlation = df[
    ["budget", "revenue", "vote_average",
     "vote_count", "popularity", "roi"]
].corr()

display(
    correlation.round(2)
)

              budget  revenue  vote_average  vote_count  popularity   roi
budget          1.00     0.73          0.09        0.59        0.51 -0.02
revenue         0.73     1.00          0.20        0.78        0.64 -0.01
vote_average    0.09     0.20          1.00        0.31        0.27  0.03
vote_count      0.59     0.78          0.31        1.00        0.78 -0.00
popularity      0.51     0.64          0.27        0.78        1.00  0.00
roi            -0.02    -0.01          0.03       -0.00        0.00  1.00